export const vietnamBankOptions = [
  { code: 'ICB', shortName: 'VietinBank', name: 'Ngân hàng TMCP Công thương Việt Nam', kind: 'BANK' },
  { code: 'VCB', shortName: 'Vietcombank', name: 'Ngân hàng TMCP Ngoại thương Việt Nam', kind: 'BANK' },
  { code: 'BIDV', shortName: 'BIDV', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', kind: 'BANK' },
  { code: 'VBA', shortName: 'Agribank', name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam', kind: 'BANK' },
  { code: 'OCB', shortName: 'OCB', name: 'Ngân hàng TMCP Phương Đông', kind: 'BANK' },
  { code: 'MB', shortName: 'MBBank', name: 'Ngân hàng TMCP Quân đội', kind: 'BANK' },
  { code: 'TCB', shortName: 'Techcombank', name: 'Ngân hàng TMCP Kỹ thương Việt Nam', kind: 'BANK' },
  { code: 'ACB', shortName: 'ACB', name: 'Ngân hàng TMCP Á Châu', kind: 'BANK' },
  { code: 'VPB', shortName: 'VPBank', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng', kind: 'BANK' },
  { code: 'TPB', shortName: 'TPBank', name: 'Ngân hàng TMCP Tiên Phong', kind: 'BANK' },
  { code: 'STB', shortName: 'Sacombank', name: 'Ngân hàng TMCP Sài Gòn Thương Tín', kind: 'BANK' },
  { code: 'HDB', shortName: 'HDBank', name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh', kind: 'BANK' },
  { code: 'VCCB', shortName: 'VietCapitalBank', name: 'Ngân hàng TMCP Bản Việt', kind: 'BANK' },
  { code: 'SCB', shortName: 'SCB', name: 'Ngân hàng TMCP Sài Gòn', kind: 'BANK' },
  { code: 'VIB', shortName: 'VIB', name: 'Ngân hàng TMCP Quốc tế Việt Nam', kind: 'BANK' },
  { code: 'SHB', shortName: 'SHB', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội', kind: 'BANK' },
  { code: 'EIB', shortName: 'Eximbank', name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam', kind: 'BANK' },
  { code: 'MSB', shortName: 'MSB', name: 'Ngân hàng TMCP Hàng Hải Việt Nam', kind: 'BANK' },
  { code: 'CAKE', shortName: 'CAKE', name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank', kind: 'BANK' },
  { code: 'Ubank', shortName: 'Ubank', name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank', kind: 'BANK' },
  { code: 'VTLMONEY', shortName: 'ViettelMoney', name: 'Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân đội', kind: 'WALLET' },
  { code: 'TIMO', shortName: 'Timo', name: 'Ngân hàng số Timo by Ban Viet Bank', kind: 'BANK' },
  { code: 'VNPTMONEY', shortName: 'VNPTMoney', name: 'VNPT Money', kind: 'WALLET' },
  { code: 'SGICB', shortName: 'SaigonBank', name: 'Ngân hàng TMCP Sài Gòn Công Thương', kind: 'BANK' },
  { code: 'BAB', shortName: 'BacABank', name: 'Ngân hàng TMCP Bắc Á', kind: 'BANK' },
  { code: 'MOMO', shortName: 'MoMo', name: 'CTCP Dịch Vụ Di Động Trực Tuyến', kind: 'WALLET' },
  { code: 'PVDB', shortName: 'PVcomBank Pay', name: 'Ngân hàng TMCP Đại Chúng Việt Nam - Ngân hàng số', kind: 'BANK' },
  { code: 'PVCB', shortName: 'PVcomBank', name: 'Ngân hàng TMCP Đại Chúng Việt Nam', kind: 'BANK' },
  { code: 'MBV', shortName: 'MBV', name: 'Ngân hàng TNHH MTV Việt Nam Hiện Đại', kind: 'BANK' },
  { code: 'NCB', shortName: 'NCB', name: 'Ngân hàng TMCP Quốc Dân', kind: 'BANK' },
  { code: 'SHBVN', shortName: 'ShinhanBank', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam', kind: 'BANK' },
  { code: 'ABB', shortName: 'ABBANK', name: 'Ngân hàng TMCP An Bình', kind: 'BANK' },
  { code: 'VAB', shortName: 'VietABank', name: 'Ngân hàng TMCP Việt Á', kind: 'BANK' },
  { code: 'NAB', shortName: 'NamABank', name: 'Ngân hàng TMCP Nam Á', kind: 'BANK' },
  { code: 'PGB', shortName: 'PGBank', name: 'Ngân hàng TMCP Thịnh vượng và Phát triển', kind: 'BANK' },
  { code: 'VIETBANK', shortName: 'VietBank', name: 'Ngân hàng TMCP Việt Nam Thương Tín', kind: 'BANK' },
  { code: 'BVB', shortName: 'BaoVietBank', name: 'Ngân hàng TMCP Bảo Việt', kind: 'BANK' },
  { code: 'SEAB', shortName: 'SeABank', name: 'Ngân hàng TMCP Đông Nam Á', kind: 'BANK' },
  { code: 'COOPBANK', shortName: 'COOPBANK', name: 'Ngân hàng Hợp tác xã Việt Nam', kind: 'BANK' },
  { code: 'LPB', shortName: 'LPBank', name: 'Ngân hàng TMCP Lộc Phát Việt Nam', kind: 'BANK' },
  { code: 'KLB', shortName: 'KienLongBank', name: 'Ngân hàng TMCP Kiên Long', kind: 'BANK' },
  { code: 'KBank', shortName: 'KBank', name: 'Ngân hàng Đại chúng TNHH Kasikornbank', kind: 'BANK' },
  { code: 'MAFC', shortName: 'MAFC', name: 'Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam)', kind: 'BANK' },
  { code: 'HLBVN', shortName: 'HongLeong', name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam', kind: 'BANK' },
  { code: 'KEBHANAHN', shortName: 'KEBHanaHN', name: 'Ngân hàng KEB Hana - Chi nhánh Hà Nội', kind: 'BANK' },
  { code: 'KEBHANAHCM', shortName: 'KEBHanaHCM', name: 'Ngân hàng KEB Hana - Chi nhánh Thành phố Hồ Chí Minh', kind: 'BANK' },
  { code: 'CITIBANK', shortName: 'Citibank', name: 'Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội', kind: 'BANK' },
  { code: 'CBB', shortName: 'CBBank', name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam', kind: 'BANK' },
  { code: 'CIMB', shortName: 'CIMB', name: 'Ngân hàng TNHH MTV CIMB Việt Nam', kind: 'BANK' },
  { code: 'DBS', shortName: 'DBSBank', name: 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh', kind: 'BANK' },
  { code: 'Vikki', shortName: 'Vikki', name: 'Ngân hàng TNHH MTV Số Vikki', kind: 'BANK' },
  { code: 'VBSP', shortName: 'VBSP', name: 'Ngân hàng Chính sách Xã hội', kind: 'BANK' },
  { code: 'GPB', shortName: 'GPBank', name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu', kind: 'BANK' },
  { code: 'KBHCM', shortName: 'KookminHCM', name: 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh', kind: 'BANK' },
  { code: 'KBHN', shortName: 'KookminHN', name: 'Ngân hàng Kookmin - Chi nhánh Hà Nội', kind: 'BANK' },
  { code: 'WVN', shortName: 'Woori', name: 'Ngân hàng TNHH MTV Woori Việt Nam', kind: 'BANK' },
  { code: 'VRB', shortName: 'VRB', name: 'Ngân hàng Liên doanh Việt - Nga', kind: 'BANK' },
  { code: 'HSBC', shortName: 'HSBC', name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)', kind: 'BANK' },
  { code: 'IBK - HN', shortName: 'IBKHN', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội', kind: 'BANK' },
  { code: 'IBK - HCM', shortName: 'IBKHCM', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh', kind: 'BANK' },
  { code: 'IVB', shortName: 'IndovinaBank', name: 'Ngân hàng TNHH Indovina', kind: 'BANK' },
  { code: 'UOB', shortName: 'UnitedOverseas', name: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh', kind: 'BANK' },
  { code: 'NHB HN', shortName: 'Nonghyup', name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội', kind: 'BANK' },
  { code: 'SCVN', shortName: 'StandardChartered', name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam', kind: 'BANK' },
  { code: 'PBVN', shortName: 'PublicBank', name: 'Ngân hàng TNHH MTV Public Việt Nam', kind: 'BANK' },
] as const;
