export const RETURN_REQUEST_STATUSES = [
  'REQUESTED',
  'SUBMITTED',
  'PENDING_PAYMENT_CONFIRMATION',
  'PENDING_ADMIN_REVIEW',
  'APPROVED',
  'IN_RETURN_TRANSIT',
  'REJECTED',
  'RECEIVED',
  'RECEIVED_AND_INSPECTING',
  'ACCEPTED_FOR_REFUND',
  'REFUNDED',
  'CLOSED',
] as const;

export type ReturnRequestStatus = (typeof RETURN_REQUEST_STATUSES)[number];

export const ACTIVE_RETURN_REQUEST_STATUSES: ReturnRequestStatus[] = [
  'REQUESTED',
  'SUBMITTED',
  'PENDING_PAYMENT_CONFIRMATION',
  'PENDING_ADMIN_REVIEW',
  'APPROVED',
  'IN_RETURN_TRANSIT',
  'RECEIVED',
  'RECEIVED_AND_INSPECTING',
  'ACCEPTED_FOR_REFUND',
  'REFUNDED',
  'CLOSED',
];

export const RETURN_REFUND_METHODS = ['ORIGINAL_PAYMENT', 'WALLET_CREDIT'] as const;

export type RefundMethod = (typeof RETURN_REFUND_METHODS)[number];

export const REFUND_WORKFLOW_STATUSES = [
  'NOT_APPLICABLE',
  'LOCKED_UNTIL_PAYMENT_CONFIRMED',
  'PENDING',
  'PROCESSING',
  'PARTIALLY_REFUNDED',
  'REFUNDED',
  'FAILED',
  'MANUAL_REVIEW',
] as const;

export type RefundWorkflowStatus = (typeof REFUND_WORKFLOW_STATUSES)[number];

/** Valid state machine transitions for return requests. */
export const RETURN_REQUEST_TRANSITIONS: Record<ReturnRequestStatus, ReturnRequestStatus[]> = {
  REQUESTED: ['APPROVED', 'REJECTED'],
  SUBMITTED: ['PENDING_PAYMENT_CONFIRMATION', 'PENDING_ADMIN_REVIEW', 'REJECTED'],
  PENDING_PAYMENT_CONFIRMATION: ['PENDING_ADMIN_REVIEW', 'REJECTED'],
  PENDING_ADMIN_REVIEW: ['APPROVED', 'REJECTED'],
  APPROVED: ['IN_RETURN_TRANSIT', 'RECEIVED_AND_INSPECTING'],
  IN_RETURN_TRANSIT: ['RECEIVED_AND_INSPECTING'],
  REJECTED: [],
  RECEIVED: ['ACCEPTED_FOR_REFUND', 'CLOSED'],
  RECEIVED_AND_INSPECTING: ['ACCEPTED_FOR_REFUND', 'REJECTED'],
  ACCEPTED_FOR_REFUND: ['REFUNDED', 'CLOSED'],
  REFUNDED: [],
  CLOSED: [],
};
